---
AnnotSV ID:
    POSITION: 1
    COMMENTLIST:
        - SV length
        - SV type
AnnotSV ranking:
    POSITION: 2
SV chrom:
    POSITION: 0
#SV start:
#    POSITION: 0
SV end:
    POSITION: 0
SV length:
    POSITION: 0
SV type:
    POSITION: 3
Samples_ID:
    POSITION: 0
REF:
    POSITION: 0
ALT:
    POSITION: 0
FORMAT:
    POSITION: 0
Sample ID:
    POSITION: 0
AnnotSV type:
    POSITION: 4 #should be kept  //// specify mandatory fields for good computing
                                # check also if 2 positions are same
                                # check field need to have a position here to be included as comment
                                # check what's best position= 0 or comment the 2 lines
                                # check if field exist in annotSV 
Gene name:
    POSITION: 5
    COMMENTLIST:
        - pLI_ExAC
        - HI_CGscore
        - TriS_CGscore 
        - HI_DDDpercent
        - ACMG
        - cnvZ_ExAC
        - delZ_ExAC
        - dupZ_ExAC
        - synZ_ExAC
        - misZ_ExAC
tx:
    POSITION: 0
CDS length:
    POSITION: 0
tx length:
    POSITION: 0
location:
    POSITION: 6
location2:
    POSITION: 0
intersectStart:
    POSITION: 0
intersectEnd:
    POSITION: 0
DGV_GAIN_IDs:
    POSITION: 0
DGV_GAIN_n_samples_with_SV:
    POSITION: 0
DGV_GAIN_n_samples_tested:
    POSITION: 0
DGV_GAIN_Frequency:
    POSITION: 7
    COMMENTLIST:
        - DGV_GAIN_n_samples_with_SV
        - DGV_GAIN_n_samples_tested
DGV_LOSS_IDs:
    POSITION: 0
DGV_LOSS_n_samples_with_SV:
    POSITION: 0
DGV_LOSS_n_samples_tested:
    POSITION: 0
DGV_LOSS_Frequency:
    POSITION: 8
    COMMENTLIST:
        - DGV_LOSS_n_samples_with_SV
        - DGV_LOSS_n_samples_tested
DDD_SV:
    POSITION: 0
DDD_DUP_n_samples_with_SV:
    POSITION: 0
DDD_DUP_Frequency:
    POSITION: 9
    COMMENTLIST:
        - DDD_DUP_n_samples_with_SV
DDD_DEL_n_samples_with_SV:
    POSITION: 0
DDD_DEL_Frequency:
    POSITION: 10
    COMMENTLIST:
        - DDD_DEL_n_samples_with_SV
DDD_status:
    POSITION: 11
GD_ID:
    POSITION: 0
GD_AN:
    POSITION: 0
GD_N_HET:
    POSITION: 0
GD_N_HOMALT:
    POSITION: 0
GD_AF:
    POSITION: 0
GD_POPMAX_AF:
    POSITION: 12
    COMMENTLIST:
        - GD_AN
        - GD_N_HET
        - GD_N_HOMALT
        - GD_AF
GD_ID_others:
    POSITION: 0
1000g_event:
    POSITION: 0
IMH_ID:
    POSITION: 0
IMH_AF:
    POSITION: 13
IMH_ID_others:
    POSITION: 0
promoters:
    POSITION: 14
    COMMENTLIST:
        - TADcoordinates
#        - GHid_elite
#        - GHid_not_elite
#        - GHtype
#        - GHgene_elite
#        - GHgene_not_elite
#        - GHtissue
dbVar_event:
    POSITION: 0
dbVar_variant:
    POSITION: 0
dbVar_status:
    POSITION: 15
    COMMENTLIST:
        - dbVar_event
        - dbVar_variant
GHid_elite:
    POSITION: 0
GHid_not_elite:
    POSITION: 0
GHtype:
    POSITION: 0
GHgene_elite:
    POSITION: 0
GHgene_not_elite:
    POSITION: 0
GHtissue:
    POSITION: 0
COSMIC_ID:
    POSITION: 0
COSMIC_MUT_TYP:
    POSITION: 0
TADcoordinates:
    POSITION: 0
ENCODEexperiments:
    POSITION: 0
GCcontent_right:
    POSITION: 0
GCcontent_left:
    POSITION: 0
Repeats_coord_left:
    POSITION: 0
Repeats_type_left:
    POSITION: 0
Repeats_coord_right:
    POSITION: 0
Repeats_type_right:
    POSITION: 0
ACMG:
    POSITION: 0
HI_CGscore:
    POSITION: 19
TriS_CGscore:
    POSITION: 0
DDD_mode:
    POSITION: 16
    COMMENTLIST:
        - DDD_consequence 
DDD_consequence:
    POSITION: 0
DDD_pmids:
    POSITION: 0
HI_DDDpercent:
    POSITION: 0
synZ_ExAC:
    POSITION: 0
misZ_ExAC:
    POSITION: 0
pLI_ExAC:
    POSITION: 0
delZ_ExAC:
    POSITION: 0
dupZ_ExAC:
    POSITION: 0
cnvZ_ExAC:
    POSITION: 0
morbidGenes:
    POSITION: 17
    COMMENTLIST:
        - Mim Number
        - Phenotypes
        - Inheritance
        - morbidGenesCandidates
morbidGenesCandidates:
    POSITION: 0
Mim Number:
    POSITION: 0
Phenotypes:
    POSITION: 0
Inheritance:
    POSITION: 0
EXOMISER_GENE_PHENO_SCORE:
    POSITION: 18
    COMMENTLIST:
        - HUMAN_PHENO_EVIDENCE
        - MOUSE_PHENO_EVIDENCE
        - FISH_PHENO_EVIDENCE
HUMAN_PHENO_EVIDENCE:
    POSITION: 0
MOUSE_PHENO_EVIDENCE:
    POSITION: 0
FISH_PHENO_EVIDENCE:
    POSITION: 0
compound-htz(sample):
    POSITION: 0
#hom(sample):
    POSITION: 0
#htz(sample):
    POSITION: 0
#htz/allHom(sample):
    POSITION: 0
#htz/total(cohort):
    POSITION: 0
#total(cohort):
    POSITION: 0


