##############################################################################################
# knotAnnotSV 1.0                                                                            #	
#                                                                                            #
# knotAnnotSV: Creation of a customizable html file to visualize, filter                     # 
#                   and analyze an AnnotSV output                                            #
#                                                                                            #
# Author: Thomas Guignard 2020                                                               #
#                                                                                            #
# Copyright (C) 2020 Thomas Guignard (t-guignard@chu-montpellier.fr)                         #
#                                                                                            #
# This is part of knotAnnotSV source code.                                                   #
#                                                                                            #
# This program is free software; you can redistribute it and/or                              #
# modify it under the terms of the GNU General Public License                                #
# as published by the Free Software Foundation; either version 3                             #
# of the License, or (at your option) any later version.                                     #
#                                                                                            #
# This program is distributed in the hope that it will be useful,                            #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                             #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                              #
# GNU General Public License for more details.                                               #
#                                                                                            #
# You should have received a copy of the GNU General Public License                          #
# along with this program; If not, see <http://www.gnu.org/licenses/>.                       #
##############################################################################################
---
#### General annotations on the SV
##################################
AnnotSV_ID:    #mandatory
    POSITION: 1
    HEADERTIPS: "AnnotSV identifier"
    COMMENTLIST:
        - SV_length
        - Gene_count
ACMG_class:  # mandatory   ### Adapter le code car on a maintenant un autre nom de colonne et un réel (au lieu d'un entier de 1 à 5)
    POSITION: 2
    HEADERTIPS: "SV ranking class (from 1 to 5) following the 2020 joint consensus recommendation of ACMG and ClinGen"
    COMMENTLIST:
        - AnnotSV_ranking_score
        - AnnotSV_ranking_criteria
SV_type:
    POSITION: 3
    HEADERTIPS: "Type of the SV (DEL, DUP...)"
Annotation_mode:
    POSITION: 4 #should be kept  //// specify mandatory fields for good computing
    HEADERTIPS: "Type of annotation generated:<br>
- annotation on the SV full length (full)<br>
- annotation on each gene overlapped by the SV (split)"


### Gene annotations
####################
Gene_name:     # mandatory
    POSITION: 5
    HEADERTIPS: "Gene symbol"
    COMMENTLIST:
        - LOEUF_bin
        - GnomAD_pLI
        - ExAC_pLI
        - HI
        - TS
        - DDD_HI_percent
        - ACMG
        - ExAC_cnvZ
        - ExAC_delZ
        - ExAC_dupZ
        - ExAC_synZ
        - ExAC_misZ
        - DDD_status
        - DDD_mode
        - DDD_consequence
        - DDD_disease
        - DDD_pmid
Location:
    POSITION: 6
    RENAME: "Location"
    HEADERTIPS: "SV location in the gene’s<br>
Values: txStart, txEnd, exon’i’, intron’i’ <br>
e.g. « txStart-exon3 »"
    COMMENTLIST:
        - Location2
        - Tx
        - Exon_count
        - Overlapped_tx_length
        - Overlapped_CDS_length
        - Overlapped_CDS_percent
        - Frameshift
        - Dist_nearest_SS
        - Nearest_SS_type
        - Intersect_start
        - Intersect_end
OMIM_phenotype:
    POSITION: 7
    RENAME: "OMIM phenotype"
    HEADERTIPS: "e.g. Charcot-Marie-Tooth disease"
    COMMENTLIST:
        - OMIM_ID
        - OMIM_inheritance
        - OMIM_morbid
        - OMIM_morbid_candidate
Exomiser_gene_pheno_score:
    POSITION: 8
    RENAME: "Exomiser score"
    HEADERTIPS: "Exomiser score showing how close each overlapped gene is to the patient phenotype<br>
    Consistent phenotype: score > 0.5<br>
    Highly specific and consistent phenotype: score > 0.7"
    COMMENTLIST:
        - Human_pheno_evidence
        - Mouse_pheno_evidence
        - Fish_pheno_evidence

### Annotations done with regulatory elements
#############################################
RE_gene:
    POSITION: 9
    RENAME: "Regulatory elements"
    HEADERTIPS: "Name of the genes regulated by a regulatory element overlapped with the SV to annotate."

### Annotations done with benign SV
###################################
B_gain_source:
    POSITION: 10
    RENAME: "Benign SV sources"
    COMMENTLIST:
        - B_gain_coord
B_loss_source:
    POSITION: 11
    RENAME: "Benign SV sources"
    COMMENTLIST:
        - B_loss_coord

### Annotations done with pathogenic SV
#######################################
P_gain_coord:
    POSITION: 12
    RENAME: "Pathogenic SV sources"
    COMMENTLIST:
        - P_gain_source
        - P_gain_phen
        - P_gain_hpo
P_loss_coord:
    POSITION: 13
    RENAME: "Pathogenic SV sources"
    COMMENTLIST:
        - P_loss_source
        - P_loss_phen
        - P_loss_hpo

### Annotations done with pathogenic snv/indel
##############################################
P_snvindel_nb:
    POSITION: 14
    RENAME: "Number of pathogenic SNV/indel overlapped"
    COMMENTLIST:
        - P_snvindel_phen


### Annotations of the breakpoints
##################################
ENCODE_blacklist_characteristics_left:
    POSITION: 15
    RENAME: "ENCODE blacklist characteristics left"
    HEADERTIPS: "ENCODE blacklist regions characteristics around the left SV breakpoint (+/- 100bp)"
    COMMENTLIST:
        - ENCODE_blacklist_left
        - SegDup_left
        - Repeat_coord_left
        - Repeat_type_left
        - Gap_left
        - GC_content_left
ENCODE_blacklist_characteristics_right:
    POSITION: 16
    RENAME: "ENCODE blacklist characteristics right"
    HEADERTIPS: "ENCODE blacklist regions characteristics around the right SV breakpoint (+/- 100bp)"
    COMMENTLIST:
        - ENCODE_blacklist_right
        - SegDup_right
        - Repeat_coord_right
        - Repeat_type_right
        - Gap_right
        - GC_content_right

SV_chrom:
    POSITION: 0
SV_start:
    POSITION: 0
SV_end:
    POSITION: 0
SV_length:
    POSITION: 0
Samples_ID:
    POSITION: 0
REF:
    POSITION: 0
ALT:
    POSITION: 0
FORMAT:
    POSITION: 0
TAD_coordinate:
    POSITION: 0
ENCODE_experiment:
    POSITION: 0
compound-htz(sample):
    POSITION: 0
Count_hom(sample):
    POSITION: 0
Count_htz(sample):
    POSITION: 0
Count_htz/allHom(sample):
    POSITION: 0
Count_htz/total(cohort):
    POSITION: 0
Count_total(cohort):
    POSITION: 0


